baseurl: 
markdown: kramdown
permalink: pretty
kramdown:
  parse_block_html: true
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

title: Trichem Pvt. Ltd.
logo: /img/logo.png
email: enquiry@chemcorp.in
enquiryemail: enquiry@chemcorp.in
links:
  - title: About Us
    id: aboutus
  - title: Team
    id: team  
  - title: Products
    id: products
  - title: Services
    id: services
  - title: Contact Us
    id: contactus

people:
- name: Mr. Chandrakant J. Shah
  pic: cshah
  position: Director

- name: Mr. Harshad J. Shah
  pic: hshah
  position: Director

- name: Mr. Nilesh C. Shah
  pic: nshah
  position: Director

- name: Mr. Ketan C. Shah
  pic: kshah
  position: Director,

#PRODUCTS POPUP
industries:
  - title: Ethyl 3 Ethoxy Propionate Extra large
    image: 'pharma.jpeg'
    id: 1
    products: [ 
      1-BROMO-3-CHLOROPROPANE,
      ACETONITRILE,
      ALLYL CHLORIDE,
      ANILINE,
      CHLOROFORM,
      D M F,
      DI ISO PROPYLETHER,
      DI METHYL SULFOXIDE,
      EPICHLOROHYDRIN,
      GLYCERIN -USP,
      HEPTANE,
      HYDRAZINE HYDRATE,
      HYDROXYLAMINE SULPHATE,
      N PROPANOL,
      O N  T ,
      PHENOL,
      SUCCINIC ACID  ,
      TERTIARY BUTANOL,
      TETRAHYDROFURAN,
   ]
  - title: ADHESIVES AND SEALANTS
    image: 'adhesive.jpeg'
    id: 2
    products: [ 
      2 ETHYL HEXANOIC ACID  (S),
      ACRYLAMIDE,
      ALLYL CHLORIDE,
      BUTYL CARBITOL, 
      CYCLO HEXANONE,
      DI METHYL SULFOXIDE, 
      EPICHLOROHYDRIN, 
      FORMIC ACID,
      GLYCERIN -USP,
      HEPTANE,
      METHYL METHACRYLATE (S),
      MYRISTIC ACID (S),
      OLEIC ACID  (S),
      PALMITIC ACID,
      PENTAERYTHRITOL,
      PROPYLENE CARBONATE (S),
      REFINED NAPHTHALENE (S),
      TETRAHYDROFURAN,
      TRICHLORO ETHYLENE, 
      TRIETHANOLAMINE 85,
      TRIMETHYLOL PROPANE,
    ]
  - title: PAINTS AND COATINGS
    image: 'paint.jpeg'
    id: 3
    products: [
      2 ETHYL HEXANOIC ACID, 
      ACRYLAMIDE,
      ACRYLIC ACID,
      ALLYL CHLORIDE,
      CYCLO HEXANONE,
      CYCLO HEXYLAMINE,
      DI ISO PROPYLETHER, 
      DI METHYL SULFOXIDE, 
      EPICHLOROHYDRIN, 
      GLYCERIN -USP,
      HEPTANE,
      METHYL METHACRYLATE,
      N PROPANOL,
      NEOPENTYL GLYCOL,
      NONYL PHENOL,
      OLEIC ACID,  
      PENTAERYTHRITOL,
      PHTHALIC ANHYDRIDE,
      PROPYLENE CARBONATE,
      REFINED NAPHTHALENE,
      TETRAHYDROFURAN,
      TRIMETHYLOL PROPANE
    ]
  - title: AGROCHEMICALS
    image: 'agro.jpg'
    id: 4
    products: [
      1-BROMO-3-CHLOROPROPANE,
      ACETONITRILE,
      ANILINE,
      CYCLO HEXANONE,
      FORMIC ACID,
      GLYCERIN -USP,
      HEPTANE,
      HYDRAZINE HYDRATE,
      MONOETHANOL AMINE (Fertilisers),
      MYRISTIC ACID,
      NONYL PHENOL (pesticides),
      O N  T,
      PALMITIC ACID ,
      REFINED NAPHTHALENE,
      TRICHLORO ETHYLENE ,
      TRIETHANOLAMINE 85,
    ]
  - title: FUEL AND FUEL ADDITIVES
    image: 'fuel.jpg'
    id: 5
    products: [
      DI ISO PROPYLETHER, 
      GLYCERIN -USP,
      TERTIARY BUTANOL
    ]
  - title: WATER TREATEMENT
    image: 'water.jpeg'
    id: 6
    products: [
      ACRYLAMIDE,
      ALLYL CHLORIDE,
      CYCLO HEXYLAMINE,
      EPICHLOROHYDRIN ,
      HYDRAZINE HYDRATE,
      METHYL METHACRYLATE,
    ]
  - title: INKS, DYES AND PIGMENTS
    image: 'ink.jpeg'
    id: 7
    products: [
      2 ETHYL HEXANOIC ACID, 
      ANILINE,
      ANTHRAQUINONE,
      BUTYL CARBITOL,  
      EPICHLOROHYDRIN, 
      HYDROQUINONE, 
      METHYL METHACRYLATE,
      N PROPANOL, 
      O N  T ,
      P T O P,
      PHTHALIC ANHYDRIDE,
      REFINED NAPHTHALENE, 
      TRIMETHYLOL PROPANE
    ]
  - title: LUBRICANTS
    image: 'lubricant.jpeg'
    id: 8
    products: [
      ACRYLIC ACID,
      MYRISTIC ACID,
      N PROPANOL,
      NEOPENTYL GLYCOL,
      OLEIC ACID,  
      PALMITIC ACID, 
      PENTAERYTHRITOL,
      TRIETHANOLAMINE 85
    ]
  - title: TEXTILES
    image: 'textile.jpeg'
    id: 9
    products: [
      ACRYLAMIDE,
      BUTYL CARBITOL,  
      EPICHLOROHYDRIN, 
      FORMIC ACID,
      GLYCERIN -USP,
      HYDROXYLAMINE SULPHATE,
      NEOPENTYL GLYCOL,
      OLEIC ACID,  
      P T O P,
      PENTAERYTHRITOL,
      PHENOL,
      TRIETHANOLAMINE 85,
      TRIMETHYLOL PROPANE
    ]
  - title: RESINS
    image: 'resin.jpg'
    id: 10
    products: [
      ANILINE,
      BISPHENOL A ,
      EPICHLOROHYDRIN ,
      MALEIC ANHYDRIDE ,
      Methyl methacrylate,
      NEOPENTYL GLYCOL,
      PENTAERYTHRITOL,
      PHENOL,
      PHTHALIC ANHYDRIDE,
    ]



# PRODUCTS PAGE 
products: 
  1-BROMO-3-CHLOROPROPANE,CHINA, 109-70-6,250KGS,,
  2 ETHYL HEXANOIC ACID,GERMANY,149-57-5,185KGS,,
  ACETONITRILE,TAIWAN,75-05-8,160KGS,,
  ACRYLAMIDE,CHINA,79-06-1,25KGS,,
  ACRYLIC ACID,CHINA,79-10-7,200KGS,,
  ALLYL CHLORIDE,JAPAN,107-05-1,180KGS,,
  ANILINE,CHINA,62-53-3,200KGS,,
  ANTHRAQUINONE,CZECH,84-65-1,20KGS,,
  BISPHENOL A,KOREA, 80-05-7,25KGS,,
  BUTYL CARBITOL,U.K,112-34-5,200KGS,,
  CHLOROFORM,RUSSIA,67-66-3,290KGS,,
  CYCLO HEXANONE,TAIWAN,108-94-1,190KGS,,
  CYCLO HEXYLAMINE,CZECH,108-91-8,175KGS,,
  D M F,CHINA,68-12-2,190KGS,,
  DI ISO PROPYLETHER,GERMANY,108-20-3,143KGS,,
  DI METHYL SULFOXIDE,CHINA, 67-68-5,225KGS,,
  EPICHLOROHYDRIN,KOREA, 106-89-8,240KGS,,
  FORMAMIDE,JAPAN,75-12-7,220KGS,,
  FORMIC ACID,CHINA,64-18-6,35KGS,,
  GLYCERIN-USP,MALAYSIA,56-81-5,250KGS,,
  HEPTANE,ISRAEL,N/A,134KGS,,
  HYDRAZINE HYDRATE,GERMANY,302-01-2,200KGS,,
  HYDROQUINONE,ITALY,123-31-9,25KGS,,
  HYDROXYLAMINE SULPHATE,RUSSIA,233-118-8,25KGS,,
  M A A,CHINA, 79-41-4,200KGS,,
  MALEIC ANHYDRIDE,MALAYSIA,108-31-6,25KGS,,
  MERCURY METAL,U S A,7439-97-6,34.5KGS,,
  METHYL METHACRYLATE,CHINA,80-62-6,180KGS,,
  MONOETHANOL AMINE,U S A,141-43-5,205KGS,,
  MYRISTIC ACID,MALAYSIA,544-63-8,25KGS,,
  N PROPANOL,TAIWAN,71-23-8,165KGS,,
  NEOPENTYL GLYCOL,JAPAN/KOREA, 126-30-7,25KGS,,
  NONYL PHENOL,TAIWAN,25154-52-3,190KGS,,
  O N  T,GERMANY,88-72-2,230KGS,,
  OLEIC ACID,MALAYSIA,112-80-1,180KGS,,
  P T O P,KOREA,140-66-9,25KGS,,
  PALMITIC ACID,MALAYSIA,57-10-3,25KGS,,
  PENTAERYTHRITOL,TURKEY,115-77-5,25KGS,,
  PHENOL,TAIWAN/KOREA,108-95-2,200/210KGS,,
  PHTHALIC ANHYDRIDE,INDONESIA, 85-44-9,25KGS,,
  PROPYLENE CARBONATE,CHINA, 108-32-7,250KGS,,
  REFINED NAPHTHALENE,CZECH,91-20-3,20KGS,,
  SUCCINIC ACID,CHINA,110-15-6,25KGS,,
  TERTIARY BUTANOL,JAPAN,75-65-0,155KGS,,
  TETRAHYDROFURAN,TAIWAN/SAUDI,109-99-9,180KGS,,
  TRICHLOROETHYLENE,JAPAN,79-01-6,290KGS,,
  TRIETHANOLAMINE 85,IRAN,79-01-6,230KGS,,
  TRIETHYL ORTHOFORMATE,CHINA,122-51-0,190KGS,,
  TRIMETHYLOL PROPANE,SWEDEN,77-99-6,25KGS,,



description: "DESCRIBE YOUR PRODUCT"

keywords: " Chemical Corp,
      Chemical Corp Pvt. Ltd.,
      Chemical Suppliers,
      Quality Products,
      Quality Chemicals,
      Best Chemicals,
      Best Chemical,
      Service,
      Best Service,
      PHARMACEUTICALS,
      Adhesives and Sealants,
      Paints and coatings,
      Agrochemicals, 
      Fuel and fuel additives,
      Water Treatement,
      inks, Dyes and Pigments,
      Lubricants,
      Textiles,
      Resins,
      1-BROMO-3-CHLOROPROPANE,
      ACETONITRILE,
      ALLYL CHLORIDE,
      ANILINE,
      CHLOROFORM,
      D M F,
      DI ISO PROPYLETHER,
      DI METHYL SULFOXIDE,
      EPICHLOROHYDRIN,
      GLYCERIN -USP,
      HEPTANE,
      HYDRAZINE HYDRATE,
      HYDROXYLAMINE SULPHATE,
      N PROPANOL,
      O N T,
      PHENOL,
      SUCCINIC ACID  ,
      TERTIARY BUTANOL,
      TETRAHYDROFURAN,
      2 ETHYL HEXANOIC ACID  (S),
      ACRYLAMIDE,
      ALLYL CHLORIDE,
      BUTYL CARBITOL, 
      CYCLO HEXANONE,
      DI METHYL SULFOXIDE, 
      EPICHLOROHYDRIN, 
      FORMIC ACID,
      GLYCERIN - USP,
      HEPTANE,
      METHYL METHACRYLATE (S),
      MYRISTIC ACID (S),
      OLEIC ACID  (S),
      PALMITIC ACID,
      PENTAERYTHRITOL,
      PROPYLENE CARBONATE (S),
      REFINED NAPHTHALENE (S),
      TETRAHYDROFURAN,
      TRICHLORO ETHYLENE, 
      TRIETHANOLAMINE 85,
      TRIMETHYLOL PROPANE,
      2 ETHYL HEXANOIC ACID, 
      ACRYLAMIDE,
      ACRYLIC ACID,
      ALLYL CHLORIDE,
      CYCLO HEXANONE,
      CYCLO HEXYLAMINE,
      DI ISO PROPYLETHER, 
      DI METHYL SULFOXIDE, 
      EPICHLOROHYDRIN, 
      GLYCERIN -USP,
      HEPTANE,
      METHYL METHACRYLATE,
      N PROPANOL,
      NEOPENTYL GLYCOL,
      NONYL PHENOL,
      OLEIC ACID,  
      PENTAERYTHRITOL,
      PHTHALIC ANHYDRIDE,
      PROPYLENE CARBONATE,
      REFINED NAPHTHALENE,
      TETRAHYDROFURAN,
      TRIMETHYLOL PROPANE,
      ANILINE,
      BISPHENOL A ,
      EPICHLOROHYDRIN ,
      MALEIC ANHYDRIDE ,
      Methyl methacrylate,
      NEOPENTYL GLYCOL,
      PENTAERYTHRITOL,
      PHENOL,
      PHTHALIC ANHYDRIDE,
Buy 1-BROMO-3-CHLOROPROPANE,
Buy 2 ETHYL HEXANOIC ACID,
Buy ACETONITRILE,
Buy ACRYLAMIDE,
Buy ACRYLIC ACID,
Buy ALLYL CHLORIDE,
Buy ANILINE,
Buy ANTHRAQUINONE,
Buy BISPHENOL A,
Buy BUTYL CARBITOL,
Buy CHLOROFORM,
Buy CYCLO HEXANONE,
Buy CYCLO HEXYLAMINE,
Buy D M F,
Buy DI ISO PROPYLETHER,
Buy DI METHYL SULFOXIDE,
Buy EPICHLOROHYDRIN,
Buy FORMAMIDE,
Buy FORMIC ACID,
Buy GLYCERIN -USP,
Buy HEPTANE,
Buy HYDRAZINE HYDRATE,
Buy HYDROQUINONE,
Buy HYDROXYLAMINE SULPHATE,
Buy M A A,
Buy MALEIC ANHYDRIDE,
Buy MERCURY METAL,
Buy METHYL METHACRYLATE,
Buy MONOETHANOL AMINE,
Buy MYRISTIC ACID,
Buy N PROPANOL,
Buy NEOPENTYL GLYCOL,
Buy NONYL PHENOL,
Buy O N  T,
Buy OLEIC ACID,
Buy P T O P,
Buy PALMITIC ACID,
Buy PENTAERYTHRITOL,
Buy PHENOL,
Buy PHTHALIC ANHYDRIDE,
Buy PROPYLENE CARBONATE,
Buy REFINED NAPHTHALENE,
Buy SUCCINIC ACID,
Buy TERTIARY BUTANOL,
Buy TETRAHYDROFURAN,
Buy TRICHLOROETHYLENE,
Buy TRIETHANOLAMINE 85,
Buy TRIETHYL ORTHOFORMATE,
Buy TRIMETHYLOL PROPANE,
Chemical Importer,
Buy Chemicals,
Sell Chemical,
Chemical Seller,
Mumbai,
India,
Maharashtra,
Hyderabad,
Bulk,
Bulk Chemicals,
Chemical,
Chemicals,
Online,
1-BROMO-3-CHLOROPROPANE,CHINA, 109-70-6,250KGS,,
  2 ETHYL HEXANOIC ACID,GERMANY,149-57-5,185KGS,,
  ACETONITRILE,TAIWAN,75-05-8,160KGS,,
  ACRYLAMIDE,CHINA,79-06-1,25KGS,,
  ACRYLIC ACID,CHINA,79-10-7,200KGS,,
  ALLYL CHLORIDE,JAPAN,107-05-1,180KGS,,
  ANILINE,CHINA,62-53-3,200KGS,,
  ANTHRAQUINONE,CZECH,84-65-1,20KGS,,
  BISPHENOL A,KOREA, 80-05-7,25KGS,,
  BUTYL CARBITOL,U.K,112-34-5,200KGS,,
  CHLOROFORM,RUSSIA,67-66-3,290KGS,,
  CYCLO HEXANONE,TAIWAN,108-94-1,190KGS,,
  CYCLO HEXYLAMINE,CZECH,108-91-8,175KGS,,
  D M F,CHINA,68-12-2,190KGS,,
  DI ISO PROPYLETHER,GERMANY,108-20-3,143KGS,,
  DI METHYL SULFOXIDE,CHINA, 67-68-5,225KGS,,
  EPICHLOROHYDRIN,KOREA, 106-89-8,240KGS,,
  FORMAMIDE,JAPAN,75-12-7,220KGS,,
  FORMIC ACID,CHINA,64-18-6,35KGS,,
  GLYCERIN-USP,MALAYSIA,56-81-5,250KGS,,
  HEPTANE,ISRAEL,N/A,134KGS,,
  HYDRAZINE HYDRATE,GERMANY,302-01-2,200KGS,,
  HYDROQUINONE,ITALY,123-31-9,25KGS,,
  HYDROXYLAMINE SULPHATE,RUSSIA,233-118-8,25KGS,,
  M A A,CHINA, 79-41-4,200KGS,,
  MALEIC ANHYDRIDE,MALAYSIA,108-31-6,25KGS,,
  MERCURY METAL,U S A,7439-97-6,34.5KGS,,
  METHYL METHACRYLATE,CHINA,80-62-6,180KGS,,
  MONOETHANOL AMINE,U S A,141-43-5,205KGS,,
  MYRISTIC ACID,MALAYSIA,544-63-8,25KGS,,
  N PROPANOL,TAIWAN,71-23-8,165KGS,,
  NEOPENTYL GLYCOL,JAPAN/KOREA, 126-30-7,25KGS,,
  NONYL PHENOL,TAIWAN,25154-52-3,190KGS,,
  O N T,GERMANY,88-72-2,230KGS,,
  OLEIC ACID,MALAYSIA,112-80-1,180KGS,,
  P T O P,KOREA,140-66-9,25KGS,,
  PALMITIC ACID,MALAYSIA,57-10-3,25KGS,,
  PENTAERYTHRITOL,TURKEY,115-77-5,25KGS,,
  PHENOL,TAIWAN/KOREA,108-95-2,200/210KGS,,
  PHTHALIC ANHYDRIDE,INDONESIA, 85-44-9,25KGS,,
  PROPYLENE CARBONATE,CHINA, 108-32-7,250KGS,,
  REFINED NAPHTHALENE,CZECH,91-20-3,20KGS,,
  SUCCINIC ACID,CHINA,110-15-6,25KGS,,
  TERTIARY BUTANOL,JAPAN,75-65-0,155KGS,,
  TETRAHYDROFURAN,TAIWAN/SAUDI,109-99-9,180KGS,,
  TRICHLOROETHYLENE,JAPAN,79-01-6,290KGS,,
  TRIETHANOLAMINE 85,IRAN,79-01-6,230KGS,,
  TRIETHYL ORTHOFORMATE,CHINA,122-51-0,190KGS,,
  TRIMETHYLOL PROPANE,SWEDEN,77-99-6,25KGS,,
  Goodwill"





