baseurl: 
markdown: kramdown
permalink: pretty
kramdown:
  parse_block_html: true
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

title: Trichem Pvt. Ltd.
logo: /img/logo.png
email: enquiry@chemcorp.in
enquiryemail: enquiry@chemcorp.in
links:
  - title: About Us
    id: aboutus
  - title: Team
    id: team  
  - title: Products
    id: products
  - title: Services
    id: services
  - title: Contact Us
    id: contactus

people:
- name: Mr. Chandrakant J. Shah
  pic: cshah
  position: Director

- name: Mr. Harshad J. Shah
  pic: hshah
  position: Director

- name: Mr. Nilesh C. Shah
  pic: nshah
  position: Director

- name: Mr. Ketan C. Shah
  pic: kshah
  position: Director,

#PRODUCTS POPUP
industries:
  - title: N-Propyl Acetate (14)
    image: 'pharma.jpeg'
    id: 1
    cas: 109-60-4
    size: 180  Kgs (MS)
    usage: [
        Coatings - Automotive OEM,
        Coatings - Automotive Refinish,
        Coatings - Can and Coil,
        Coatings - General Industrial,
        Coatings - Industrial Maintenance and Marine,
        Coatings - Industrial Wood,
        Coatings - Transportation,
        Cosmetics & Personal Care - Nail Care & Flavoring Agent,
        Graphic Arts - Printing Inks,
    ]
    attributes: [
        Good solvent activity,
        High electrical resistance,
        Inert - Nonfood use,
        Low MIR value,
        Low surface tension,
        Low water solubility,
        Medium evaporation rate,
        Mild odor,
        Non-HAP,
        Non-SARA,
        Predicted to be readily biodegradable*,
        REACH compliant,
        Urethane grade
    ]

  - title: N-Propyl Alcohol Pure (45)
    image: 'adhesive.jpeg'
    id: 2
    cas: 109-60-4
    size: 180  Kgs (MS)
    applications: [ 
    ]
  - title: Iso Propyl Acetate (06)
    image: 'paint.jpeg'
    id: 3
    cas: 109-60-4
    size: 180  Kgs (MS)
    applications: [
    ]
  - title: Iso Butyl Acetate (40)
    image: 'agro.jpg'
    id: 4
    cas: 109-60-4
    size: 180  Kgs (MS)
    applications: [
    ]
  - title: Ethyl 3 Ethoxy Propionate [EEP] (67)
    image: 'fuel.jpg'
    id: 5
    cas: 109-60-4
    size: 180  Kgs (MS)
    applications: [

    ]
  - title: N-Butyl Propionate (46)
    image: 'water.jpeg'
    id: 6
    cas: 109-60-4
    size: 180  Kgs (MS)
    applications: [
    ]
  - title: N-Pentyl Propionate (47)
    image: 'ink.jpeg'
    id: 7
    cas: 109-60-4
    size: 180  Kgs (MS)
    applications: [

    ]
  - title: Flexo Solvent Tri 82 (82)
    image: 'lubricant.jpeg'
    id: 8
    cas: 109-60-4
    size: 180  Kgs (MS)
    applications: [

    ]
  - title: Flexo Solvent Tri 73 (73)
    image: 'textile.jpeg'
    id: 9
    cas: 109-60-4
    size: 180  Kgs (MS)
    applications: [
    ]